import * as docx from "docx";
import FileSaver from "file-saver";

export const generateAndDownloadDocx = async (text: string, filename: string = "transcription.docx") => {
  // Split text by newlines to create paragraphs
  const paragraphs = text.split('\n').map(line => {
    return new docx.Paragraph({
      children: [
        new docx.TextRun({
          text: line,
          size: 24, // 12pt
          font: "Arial", // Good fallback for English
        }),
      ],
      spacing: {
        after: 200, // Spacing between paragraphs
      },
      // Simple heuristic: check if line starts with Urdu unicode range to set RTL
      // Urdu unicode range is approx 0600–06FF.
      bidirectional: /[\u0600-\u06FF]/.test(line), 
    });
  });

  const doc = new docx.Document({
    sections: [
      {
        properties: {},
        children: [
          new docx.Paragraph({
            children: [
              new docx.TextRun({
                text: "Audio Transcription",
                bold: true,
                size: 32,
                color: "2563EB", // Blue-600
              }),
            ],
            spacing: {
              after: 400,
            },
          }),
          new docx.Paragraph({
            children: [
                new docx.TextRun({
                    text: `Generated by ScribeFlow on ${new Date().toLocaleString()}`,
                    italics: true,
                    size: 20,
                    color: "6B7280"
                })
            ],
            spacing: {
                after: 400
            }
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  const blob = await docx.Packer.toBlob(doc);
  
  // Handle case where FileSaver is the function (default behavior on most CDNs) 
  // or an object containing saveAs (common in some CJS-to-ESM bridges)
  const saveAs = (FileSaver as any).saveAs || FileSaver;
  saveAs(blob, filename);
};